#ifndef KEY_BITS_HPP
#define KEY_BITS_HPP

#include <GLFW/glfw3.h>

namespace as
{
    struct KEY
    {
        inline static const int SPACE = GLFW_KEY_SPACE;
        inline static const int APOSTROPHE = GLFW_KEY_APOSTROPHE;
        inline static const int COMMA = GLFW_KEY_COMMA;
        inline static const int MINUS = GLFW_KEY_MINUS;
        inline static const int PERIOD = GLFW_KEY_PERIOD;
        inline static const int SLASH = GLFW_KEY_SLASH;
        inline static const int ZERO = GLFW_KEY_0;
        inline static const int ONE = GLFW_KEY_1;
        inline static const int TWO = GLFW_KEY_2;
        inline static const int THREE = GLFW_KEY_3;
        inline static const int FOUR = GLFW_KEY_4;
        inline static const int FIVE = GLFW_KEY_5;
        inline static const int SIX = GLFW_KEY_6;
        inline static const int SEVEN = GLFW_KEY_7;
        inline static const int EIGHT = GLFW_KEY_8;
        inline static const int NINE = GLFW_KEY_9;
        inline static const int SEMICOLON = GLFW_KEY_SEMICOLON;
        inline static const int EQUAL = GLFW_KEY_EQUAL;
        inline static const int A = GLFW_KEY_A;
        inline static const int B = GLFW_KEY_B;
        inline static const int C = GLFW_KEY_C;
        inline static const int D = GLFW_KEY_D;
        inline static const int E = GLFW_KEY_E;
        inline static const int F = GLFW_KEY_F;
        inline static const int G = GLFW_KEY_G;
        inline static const int H = GLFW_KEY_H;
        inline static const int I = GLFW_KEY_I;
        inline static const int J = GLFW_KEY_J;
        inline static const int K = GLFW_KEY_K;
        inline static const int L = GLFW_KEY_L;
        inline static const int M = GLFW_KEY_M;
        inline static const int N = GLFW_KEY_N;
        inline static const int O = GLFW_KEY_O;
        inline static const int P = GLFW_KEY_P;
        inline static const int Q = GLFW_KEY_Q;
        inline static const int R = GLFW_KEY_R;
        inline static const int S = GLFW_KEY_S;
        inline static const int T = GLFW_KEY_T;
        inline static const int U = GLFW_KEY_U;
        inline static const int V = GLFW_KEY_V;
        inline static const int W = GLFW_KEY_W;
        inline static const int X = GLFW_KEY_X;
        inline static const int Y = GLFW_KEY_Y;
        inline static const int Z = GLFW_KEY_Z;
        inline static const int LEFT_BRACKET = GLFW_KEY_LEFT_BRACKET;
        inline static const int BACKSLASH = GLFW_KEY_BACKSLASH;
        inline static const int RIGHT_BRACKET = GLFW_KEY_RIGHT_BRACKET;
        inline static const int GRAVE_ACCENT = GLFW_KEY_GRAVE_ACCENT;
        inline static const int WORLD_1 = GLFW_KEY_WORLD_1;
        inline static const int WORLD_2 = GLFW_KEY_WORLD_2;
        inline static const int ESCAPE = GLFW_KEY_ESCAPE;
        inline static const int ENTER = GLFW_KEY_ENTER;
        inline static const int TAB = GLFW_KEY_TAB;
        inline static const int BACKSPACE = GLFW_KEY_BACKSPACE;
        inline static const int INSERT = GLFW_KEY_INSERT;
        inline static const int DEL = GLFW_KEY_DELETE;
        inline static const int RIGHT = GLFW_KEY_RIGHT;
        inline static const int LEFT = GLFW_KEY_LEFT;
        inline static const int DOWN = GLFW_KEY_DOWN;
        inline static const int UP = GLFW_KEY_UP;
        inline static const int PAGE_UP = GLFW_KEY_PAGE_UP;
        inline static const int PAGE_DOWN = GLFW_KEY_PAGE_DOWN;
        inline static const int HOME = GLFW_KEY_HOME;
        inline static const int END = GLFW_KEY_END;
        inline static const int CAPS_LOCK = GLFW_KEY_CAPS_LOCK;
        inline static const int SCROLL_LOCK = GLFW_KEY_SCROLL_LOCK;
        inline static const int NUM_LOCK = GLFW_KEY_NUM_LOCK;
        inline static const int PRINT_SCREEN = GLFW_KEY_PRINT_SCREEN;
        inline static const int PAUSE = GLFW_KEY_PAUSE;
        inline static const int F1 = GLFW_KEY_F1;
        inline static const int F2 = GLFW_KEY_F2;
        inline static const int F3 = GLFW_KEY_F3;
        inline static const int F4 = GLFW_KEY_F4;
        inline static const int F5 = GLFW_KEY_F5;
        inline static const int F6 = GLFW_KEY_F6;
        inline static const int F7 = GLFW_KEY_F7;
        inline static const int F8 = GLFW_KEY_F8;
        inline static const int F9 = GLFW_KEY_F9;
        inline static const int F10 = GLFW_KEY_F10;
        inline static const int F11 = GLFW_KEY_F11;
        inline static const int F12 = GLFW_KEY_F12;
        inline static const int F13 = GLFW_KEY_F13;
        inline static const int F14 = GLFW_KEY_F14;
        inline static const int F15 = GLFW_KEY_F15;
        inline static const int F16 = GLFW_KEY_F16;
        inline static const int F17 = GLFW_KEY_F17;
        inline static const int F18 = GLFW_KEY_F18;
        inline static const int F19 = GLFW_KEY_F19;
        inline static const int F20 = GLFW_KEY_F20;
        inline static const int F21 = GLFW_KEY_F21;
        inline static const int F22 = GLFW_KEY_F22;
        inline static const int F23 = GLFW_KEY_F23;
        inline static const int F24 = GLFW_KEY_F24;
        inline static const int F25 = GLFW_KEY_F25;
        inline static const int KP_0 = GLFW_KEY_KP_0;
        inline static const int KP_1 = GLFW_KEY_KP_1;
        inline static const int KP_2 = GLFW_KEY_KP_2;
        inline static const int KP_3 = GLFW_KEY_KP_3;
        inline static const int KP_4 = GLFW_KEY_KP_4;
        inline static const int KP_5 = GLFW_KEY_KP_5;
        inline static const int KP_6 = GLFW_KEY_KP_6;
        inline static const int KP_7 = GLFW_KEY_KP_7;
        inline static const int KP_8 = GLFW_KEY_KP_8;
        inline static const int KP_9 = GLFW_KEY_KP_9;
        inline static const int KP_DECIMAL = GLFW_KEY_KP_DECIMAL;
        inline static const int KP_DIVIDE = GLFW_KEY_KP_DIVIDE;
        inline static const int KP_MULTIPLY = GLFW_KEY_KP_MULTIPLY;
        inline static const int KP_SUBTRACT = GLFW_KEY_KP_SUBTRACT;
        inline static const int KP_ADD = GLFW_KEY_KP_ADD;
        inline static const int KP_ENTER = GLFW_KEY_KP_ENTER;
        inline static const int KP_EQUAL = GLFW_KEY_KP_EQUAL;
        inline static const int LEFT_SHIFT = GLFW_KEY_LEFT_SHIFT;
        inline static const int LEFT_CONTROL = GLFW_KEY_LEFT_CONTROL;
        inline static const int LEFT_ALT = GLFW_KEY_LEFT_ALT;
        inline static const int LEFT_SUPER = GLFW_KEY_LEFT_SUPER;
        inline static const int RIGHT_SHIFT = GLFW_KEY_RIGHT_SHIFT;
        inline static const int RIGHT_CONTROL = GLFW_KEY_RIGHT_CONTROL;
        inline static const int RIGHT_ALT = GLFW_KEY_RIGHT_ALT;
        inline static const int RIGHT_SUPER = GLFW_KEY_RIGHT_SUPER;
        inline static const int MENU = GLFW_KEY_MENU;
        inline static const int LAST = GLFW_KEY_MENU;
        inline static const int BUTTON_1 = GLFW_MOUSE_BUTTON_1;
        inline static const int BUTTON_2 = GLFW_MOUSE_BUTTON_2;
        inline static const int BUTTON_3 = GLFW_MOUSE_BUTTON_3;
        inline static const int BUTTON_4 = GLFW_MOUSE_BUTTON_4;
        inline static const int BUTTON_5 = GLFW_MOUSE_BUTTON_5;
        inline static const int BUTTON_6 = GLFW_MOUSE_BUTTON_6;
        inline static const int BUTTON_7 = GLFW_MOUSE_BUTTON_7;
        inline static const int BUTTON_8 = GLFW_MOUSE_BUTTON_8;
        inline static const int BUTTON_LAST = GLFW_MOUSE_BUTTON_LAST;
        inline static const int BUTTON_LEFT = GLFW_MOUSE_BUTTON_LEFT;
        inline static const int BUTTON_RIGHT = GLFW_MOUSE_BUTTON_RIGHT;
        inline static const int BUTTON_MIDDLE = GLFW_MOUSE_BUTTON_MIDDLE;
    };

}; // namespace as

#endif // KEY_BITS_HPP
